//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srs_6_testing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessLerning
    {
        public int ProcessLerningID { get; set; }
        public Nullable<int> UsersID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
